import Joi from 'joi';
import { DB_CONSTRAINTS } from '../config/constants';

/**
 * Joi validation schema for creating a new category.
 *
 * Enforces DB constraints:
 * - name: required, max length
 * - slug: optional (auto-generated by model hook if missing), max length, lowered
 * - description: optional text
 * - metaTitle: optional string, max length
 * - metaDescription: optional string, max length
 * - isActive: optional boolean
 * - sortOrder: optional integer
 */
export const createCategorySchema = Joi.object({
  name: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_NAME)
    .trim()
    .required()
    .messages({
      'string.base': 'Category name must be a string.',
      'string.max': `Category name must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_NAME} characters.`,
      'any.required': 'Category name is required.',
    }),

  slug: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_SLUG)
    .lowercase()
    .trim()
    .allow(null, '') // Allow empty so it can be generated by DB hook
    .optional()
    .messages({
      'string.base': 'Slug must be a string.',
      'string.max': `Slug must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_SLUG} characters.`,
    }),

  description: Joi.string().allow(null, '').optional().messages({
    'string.base': 'Description must be a string.',
  }),

  metaTitle: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_META_TITLE)
    .allow(null, '')
    .optional()
    .messages({
      'string.base': 'Meta title must be a string.',
      'string.max': `Meta title must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_META_TITLE} characters.`,
    }),

  metaDescription: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_META_DESCRIPTION)
    .allow(null, '')
    .optional()
    .messages({
      'string.base': 'Meta description must be a string.',
      'string.max': `Meta description must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_META_DESCRIPTION} characters.`,
    }),

  isActive: Joi.boolean().optional().messages({
    'boolean.base': 'isActive must be a boolean.',
  }),

  sortOrder: Joi.number().integer().optional().messages({
    'number.base': 'sortOrder must be a number.',
    'number.integer': 'sortOrder must be an integer.',
  }),
});

/**
 * Joi validation schema for updating an existing category.
 * All fields are optional since updates can be partial.
 */
export const updateCategorySchema = Joi.object({
  name: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_NAME)
    .trim()
    .optional()
    .messages({
      'string.base': 'Category name must be a string.',
      'string.max': `Category name must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_NAME} characters.`,
    }),

  slug: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_SLUG)
    .lowercase()
    .trim()
    .allow(null, '')
    .optional()
    .messages({
      'string.base': 'Slug must be a string.',
      'string.max': `Slug must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_SLUG} characters.`,
    }),

  description: Joi.string().allow(null, '').optional().messages({
    'string.base': 'Description must be a string.',
  }),

  metaTitle: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_META_TITLE)
    .allow(null, '')
    .optional()
    .messages({
      'string.base': 'Meta title must be a string.',
      'string.max': `Meta title must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_META_TITLE} characters.`,
    }),

  metaDescription: Joi.string()
    .max(DB_CONSTRAINTS.CATEGORY.MAX_META_DESCRIPTION)
    .allow(null, '')
    .optional()
    .messages({
      'string.base': 'Meta description must be a string.',
      'string.max': `Meta description must not exceed ${DB_CONSTRAINTS.CATEGORY.MAX_META_DESCRIPTION} characters.`,
    }),

  isActive: Joi.boolean().optional().messages({
    'boolean.base': 'isActive must be a boolean.',
  }),

  sortOrder: Joi.number().integer().optional().messages({
    'number.base': 'sortOrder must be a number.',
    'number.integer': 'sortOrder must be an integer.',
  }),
});

export default { createCategorySchema, updateCategorySchema };
