import Joi from 'joi';
import { DB_CONSTRAINTS } from '../config/constants';

/**
 * Joi validation schema for creating a new tag.
 *
 * Enforces DB constraints:
 * - name: required, max length 100
 * - slug: optional (auto-generated by model hook if missing), max length 120, lowered
 */
export const createTagSchema = Joi.object({
  name: Joi.string()
    .max(DB_CONSTRAINTS.TAG.MAX_NAME)
    .trim()
    .required()
    .messages({
      'string.base': 'Tag name must be a string.',
      'string.max': `Tag name must not exceed ${DB_CONSTRAINTS.TAG.MAX_NAME} characters.`,
      'any.required': 'Tag name is required.',
    }),

  slug: Joi.string()
    .max(DB_CONSTRAINTS.TAG.MAX_SLUG)
    .lowercase()
    .trim()
    .allow(null, '') // Allow empty so it can be generated by DB hook
    .optional()
    .messages({
      'string.base': 'Slug must be a string.',
      'string.max': `Slug must not exceed ${DB_CONSTRAINTS.TAG.MAX_SLUG} characters.`,
    }),
});

/**
 * Joi validation schema for updating an existing tag.
 * All fields are optional since updates can be partial.
 */
export const updateTagSchema = Joi.object({
  name: Joi.string()
    .max(DB_CONSTRAINTS.TAG.MAX_NAME)
    .trim()
    .optional()
    .messages({
      'string.base': 'Tag name must be a string.',
      'string.max': `Tag name must not exceed ${DB_CONSTRAINTS.TAG.MAX_NAME} characters.`,
    }),

  slug: Joi.string()
    .max(DB_CONSTRAINTS.TAG.MAX_SLUG)
    .lowercase()
    .trim()
    .allow(null, '')
    .optional()
    .messages({
      'string.base': 'Slug must be a string.',
      'string.max': `Slug must not exceed ${DB_CONSTRAINTS.TAG.MAX_SLUG} characters.`,
    }),
});

export default { createTagSchema, updateTagSchema };
